# N-Queens Hill-Climbing Implementation
This project solves the N-Queens problem using a Hill-Climbing search method. It includes a Pygame visualization that shows the board and queen positions while the algorithm runs.

In [ ]:
import random
import numpy as np
import pygame
from IPython.display import clear_output
import time

# Problem Representation
The board is represented as a list of row positions for each column. This makes it easy to test every possible move for a queen in a single column.

In [ ]:
class NQueens:
    def __init__(self, n):
        self.n = n
        self.board = [random.randint(0, n - 1) for _ in range(n)]

    def __repr__(self):
        return f"NQueens(n={self.n}, board={self.board})"

# Board Printing and Matrix Conversion
These helper functions show the board as text and convert the board state to a matrix for easy checking.

In [ ]:
def print_board(board):
    n = len(board)
    for row in range(n):
        print(' '.join('Q' if board[col] == row else '.' for col in range(n)))
    print()


def board_to_matrix(board):
    n = len(board)
    matrix = np.zeros((n, n), dtype=int)
    matrix[np.arange(n), board] = 1
    return matrix

# Conflict Detection
The heuristic counts every pair of queens that can attack each other horizontally or diagonally.

In [62]:
def calculate_conflicts(board):
    n = len(board)
    conflicts = 0
    for i in range(n):
        for j in range(i + 1, n):
            if board[i] == board[j] or abs(board[i] - board[j]) == abs(i - j):
                conflicts += 1
    return conflicts

# Hill-Climbing Search
Hill-climbing starts from a random board and moves to the neighbor with the lowest conflict count.

In [63]:
def hill_climbing(n, max_iterations=1000):
    state = NQueens(n)
    current_conflicts = calculate_conflicts(state.board)

    for step in range(max_iterations):
        if current_conflicts == 0:
            return state, True

        best_board = state.board
        best_conflicts = current_conflicts

        for col in range(n):
            for row in range(n):
                if row == state.board[col]:
                    continue
                new_board = state.board.copy()
                new_board[col] = row
                new_conflicts = calculate_conflicts(new_board)
                if new_conflicts < best_conflicts:
                    best_conflicts = new_conflicts
                    best_board = new_board

        if best_conflicts >= current_conflicts:
            break

        state.board = best_board
        current_conflicts = best_conflicts

    return state, False

# Pygame Visualization
The visualization draws the board and the queens in a separate window, while the notebook also prints the current state and conflict count.

In [64]:
def draw_board_pygame(screen, board, n, cell_size=60):
    for row in range(n):
        for col in range(n):
            color = (245, 245, 245) if (row + col) % 2 == 0 else (185, 185, 185)
            pygame.draw.rect(screen, color, (col * cell_size, row * cell_size, cell_size, cell_size))

    for col, row in enumerate(board):
        center = (col * cell_size + cell_size // 2, row * cell_size + cell_size // 2)
        pygame.draw.circle(screen, (220, 50, 50), center, cell_size // 3)


def visualize_hill_climbing(n, max_iterations=1000):
    state = NQueens(n)
    current_conflicts = calculate_conflicts(state.board)

    pygame.init()
    cell_size = 60
    screen = pygame.display.set_mode((n * cell_size, n * cell_size))
    pygame.display.set_caption("N-Queens Hill Climbing")

    for step in range(max_iterations):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                return state, False

        screen.fill((0, 0, 0))
        draw_board_pygame(screen, state.board, n, cell_size)
        pygame.display.flip()

        clear_output(wait=True)
        print(f"Step: {step}, Conflicts: {current_conflicts}")
        print_board(state.board)
        print("Board matrix:")
        print(board_to_matrix(state.board))

        if current_conflicts == 0:
            break

        best_board = state.board
        best_conflicts = current_conflicts
        for col in range(n):
            for row in range(n):
                if row == state.board[col]:
                    continue
                new_board = state.board.copy()
                new_board[col] = row
                new_conflicts = calculate_conflicts(new_board)
                if new_conflicts < best_conflicts:
                    best_conflicts = new_conflicts
                    best_board = new_board

        if best_conflicts >= current_conflicts:
            break

        state.board = best_board
        current_conflicts = best_conflicts
        time.sleep(0.1)

    pygame.time.wait(1200)
    pygame.quit()
    return state, current_conflicts == 0

# Run Hill-Climbing with Visualization
Running this cell opens the Pygame window. The window is the visual output for the assignment.

In [65]:
n = 8
solution, success = visualize_hill_climbing(n)
print("Solution found:", success)
print("Final board:", solution.board)
print("Final board matrix:")
print(board_to_matrix(solution.board))

Step: 3, Conflicts: 3
. . . Q . . . .
. . . . . . . Q
. . Q . . . . .
. . . . . Q . .
Q . . . . . . .
. . . . . . Q .
. Q . . . . . .
. . . . Q . . .

Board matrix:
[[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]]
Solution found: False
Final board: [4, 6, 2, 0, 7, 3, 5, 1]
Final board matrix:
[[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]]


# Analyze Results and Statistics
This section checks how often the hill-climbing search solves the N-Queens problem for different board sizes.

In [ ]:
results = []
for _ in range(10):
    sol, suc = hill_climbing(8)
    results.append(suc)
print(f"Success rate for N=8: {sum(results)/len(results)}")

for n_test in [4, 6, 8]:
    results = [hill_climbing(n_test)[1] for _ in range(10)]
    print(f"Success rate for N={n_test}: {sum(results)/len(results)}")

Success rate for N=8: 0.3
Success rate for N=4: 0.5
Success rate for N=6: 0.0
Success rate for N=8: 0.1
